POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Aprendendo node",
    "description": "primeira parte dos estudos de node", 
    "duration": 1800
}

###

GET http://localhost:3333/videos

###

GET http://localhost:3333/videos?search=

###

PUT http://localhost:3333/videos/b284649a-61a8-4eec-90c5-db0c9e5a062a
Content-Type: application/json

{
    "title": "mudando título para teste",
    "description": "descrição video de teste",
    "duration": 180
}

###
DELETE http://localhost:3333/videos/b284649a-61a8-4eec-90c5-db0c9e5a062a